input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
output_test_data_path: "data/test/test_data.csv"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.1
  random_state: 3
train_params:
  model_type: "LogisticRegression"
  max_iter: 100
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop:
    - ""
  target_col: "target"

